# Generated by Django 4.2.9 on 2024-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=30)),
                ('documentID', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
                ('driver_license_number', models.CharField(max_length=200)),
                ('driver_country_of_issue', models.CharField(max_length=200)),
                ('driver_date_of_issue', models.DateField()),
                ('driver_date_of_expiry', models.DateField()),
                ('emirates_id_passport_number', models.CharField(max_length=200)),
                ('emirates_id_passport_date_of_issue', models.DateField()),
                ('emirates_id_passport_date_of_expiry', models.DateField()),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='FinesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlateNo', models.CharField(max_length=100)),
                ('PlateCode', models.CharField(max_length=100)),
                ('PlateCategory', models.CharField(max_length=100)),
                ('LicenseNo', models.CharField(max_length=100)),
                ('LicenseFrom', models.CharField(max_length=100)),
                ('TicketNo', models.CharField(max_length=100)),
                ('TicketDate', models.DateField(blank=True)),
                ('TicketTime', models.TimeField()),
                ('FinesSource', models.CharField(max_length=100)),
                ('TicketFee', models.CharField(max_length=100)),
                ('TicketStatus', models.CharField(max_length=100)),
                ('TermsoftheOffense', models.CharField(max_length=100)),
                ('Ride_ID', models.CharField(blank=True, max_length=60, null=True)),
                ('Status', models.CharField(choices=[('Not started', 'Not started'), ('Pending', 'Pending'), ('Invoiced', 'Invoiced'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Fines',
                'verbose_name_plural': 'Fines',
            },
        ),
        migrations.CreateModel(
            name='SalikDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarnsactionID', models.CharField(max_length=100)),
                ('TripDate', models.DateField(blank=True)),
                ('TripTime', models.TimeField(blank=True, null=True)),
                ('Plate', models.CharField(max_length=30)),
                ('Amount', models.CharField(max_length=30)),
                ('Ride_ID', models.CharField(blank=True, max_length=60, null=True)),
                ('UserId', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Not started', 'Not started'), ('Pending', 'Pending'), ('Invoiced', 'Invoiced'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Salik',
                'verbose_name_plural': 'Salik',
            },
        ),
        migrations.CreateModel(
            name='UserSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('Vehicle_No', models.CharField(max_length=200)),
                ('Ride_distance', models.FloatField()),
                ('Start_date', models.DateTimeField(blank=True)),
                ('End_date', models.DateTimeField(blank=True)),
                ('Ride_duration', models.DurationField()),
                ('Total_cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Add_Date', models.DateTimeField(auto_now=True)),
                ('Ride_ID', models.CharField(max_length=60)),
                ('User_PhoneNo', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Not started', 'Not started'), ('Pending', 'Pending'), ('Under process', 'Under process'), ('Upload Done', 'Upload Done'), ('Contract Closed', 'Contract Closed')], default='', max_length=20)),
                ('VehiclemodelID', models.CharField(max_length=100)),
                ('Vehiclestartlatitude', models.CharField(max_length=100)),
                ('Vehiclestartlongitude', models.CharField(max_length=100)),
                ('Vehicleendlatitude', models.CharField(max_length=100)),
                ('Vehicleendlongitude', models.CharField(max_length=100)),
                ('Userphonenumber', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
