# Generated by Django 4.2.9 on 2024-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=30)),
                ('documentID', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('Vehicle_No', models.CharField(max_length=200)),
                ('Ride_distance', models.FloatField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField(blank=True)),
                ('Ride_duration', models.DurationField()),
                ('Total_cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Add_Date', models.DateTimeField(auto_now=True)),
                ('Ride_ID', models.CharField(max_length=60)),
                ('User_PhoneNo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
            },
        ),
    ]
