# Generated by Django 4.2.9 on 2024-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='ID',
            new_name='Customer_ID',
        ),
    ]
