# Generated by Django 4.2.9 on 2024-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalikDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarnsactionID', models.CharField(max_length=30)),
                ('TripDate', models.DateField()),
                ('TripTime', models.FloatField()),
                ('Plate', models.CharField(max_length=30)),
                ('TollGate', models.CharField(max_length=30)),
                ('Amount', models.CharField(max_length=30)),
                ('PostDate', models.DateField()),
                ('TagNo', models.CharField(max_length=30)),
                ('Ride_ID',models.CharField(max_length=60, null=True, blank=True)),
                ('UserId' ,models.IntegerField(null=True, blank=True))
            ],
        ),
    ]
