# Generated by Django 4.2.9 on 2024-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_salikdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salikdetails',
            options={'verbose_name': 'Salik', 'verbose_name_plural': 'Salik'},
        ),
        migrations.RemoveField(
            model_name='salikdetails',
            name='PostDate',
        ),
        migrations.RemoveField(
            model_name='salikdetails',
            name='TagNo',
        ),
        migrations.RemoveField(
            model_name='salikdetails',
            name='TollGate',
        ),
        migrations.RemoveField(
            model_name='salikdetails',
            name='TripTime',
        ),
        migrations.AlterField(
            model_name='salikdetails',
            name='TarnsactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salikdetails',
            name='TripDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
