# Generated by Django 4.2.9 on 2024-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_salikdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salikdetails',
            name='TripTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salikdetails',
            name='TripDate',
            field=models.DateField(blank=True),
        ),
    ]
