# Generated by Django 4.2.9 on 2024-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_salikdetails_triptime_alter_salikdetails_tripdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='End_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='Start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
