# Generated by Django 4.2.9 on 2024-02-13 05:18

from django.db import migrations, models

def set_default_ride_id(apps, schema_editor):
    SalikDetails = apps.get_model('customer', 'SalikDetails')
    # Update existing rows with a default value for Ride_ID
    SalikDetails.objects.filter(Ride_ID__isnull=True).update(Ride_ID='default_value')


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_vehicledetails_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salikdetails',
            name='Ride_ID',
            field=models.CharField(max_length=60, default='default_value', blank=True, null=True),
        ),
        migrations.RunPython(set_default_ride_id), 
        migrations.AddField(
            model_name='salikdetails',
            name='UserId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
