# Generated by Django 4.2.9 on 2024-02-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_salikdetails_ride_id_alter_salikdetails_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlateNo', models.CharField(max_length=100)),
                ('PlateCode', models.CharField(max_length=100)),
                ('PlateCategory', models.CharField(max_length=100)),
                ('LicenseNo', models.CharField(max_length=100)),
                ('LicenseFrom', models.CharField(max_length=100)),
                ('TicketNo', models.CharField(max_length=100)),
                ('TicketDate', models.DateField(blank=True)),
                ('TicketTime', models.TimeField()),
                ('FinesSource', models.CharField(max_length=100)),
                ('TicketFee', models.CharField(max_length=100)),
                ('TicketStatus', models.CharField(max_length=100)),
                ('TermsoftheOffense', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fines',
                'verbose_name_plural': 'Fines',
            },
        ),
    ]
