# Generated by Django 4.2.9 on 2024-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_salikdetails_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='finesdetails',
            name='Ride_ID',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
