# Generated by Django 4.2.9 on 2024-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_finesdetails_ride_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
