# Generated by Django 4.2.9 on 2024-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_vehicledetails_options_usersaving_password_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usersaving',
        #     name='password',
        #     field=models.CharField(default='', max_length=100),
        # ),
    ]
