# Generated by Django 4.2.9 on 2024-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_usersaving_password_vehicledetails_status'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usersaving',
        #     name='password',
        #     field=models.CharField(default='', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='vehicledetails',
        #     name='Status',
        #     field=models.CharField(choices=[('Not started', 'Not started'), ('Pending', 'Pending'), ('Under process', 'Under process'), ('Upload Done', 'Upload Done'), ('Contract Closed', 'Contract Closed')], default='', max_length=20),
        # ),
    ]
